import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Plus, Search } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useSeller } from "@/lib/auth";
import { brl, dateBR, maskCpf, maskPhone } from "@/lib/format";
import { PageHeader } from "@/components/shells";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SellerStatus } from "@/components/seller-status";
export const Route=createFileRoute("/_authenticated/vendedor/leads")({head:()=>({meta:[{title:"Meus clientes | Cartão do Bairro"},{name:"description",content:"Clientes e propostas do vendedor."},{property:"og:title",content:"Meus clientes | Cartão do Bairro"},{property:"og:description",content:"Acompanhe clientes e propostas."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:SellerClients});
function SellerClients(){const{data:seller}=useSeller();const[search,setSearch]=useState("");const[filter,setFilter]=useState("todos");const{data:leads}=useQuery({queryKey:["seller-leads",seller?.id],enabled:!!seller?.id,queryFn:async()=>{const{data,error}=await supabase.from("seller_leads").select("*, plans(name,price)").eq("seller_id",seller!.id).order("created_at",{ascending:false});if(error)throw error;return data;}});const rows=useMemo(()=>{const q=search.toLowerCase().replace(/\D/g,"");return(leads??[]).filter((l)=>{const status=filter==="todos"||filter==="ativos"&&l.status==="ativo"||filter==="pendentes"&&!["ativo","perdido"].includes(l.status)||filter==="inativos"&&l.status==="perdido";const text=`${l.name} ${l.cpf??""} ${l.whatsapp??l.phone??""}`.toLowerCase();return status&&(!search||text.includes(search.toLowerCase())||text.replace(/\D/g,"").includes(q))})},[leads,search,filter]);return <div><PageHeader title="Meus clientes" description="Propostas, cadastros e situação de cada cliente" action={<Button asChild><Link to="/vendedor/nova-venda"><Plus className="size-4"/>Nova venda</Link></Button>}/><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar por nome, CPF ou WhatsApp" value={search} onChange={(e)=>setSearch(e.target.value)}/></div><select className="h-10 rounded-md border bg-background px-3 text-sm" value={filter} onChange={(e)=>setFilter(e.target.value)}><option value="todos">Todos</option><option value="ativos">Ativos</option><option value="pendentes">Pendentes</option><option value="inativos">Inativos</option></select></div><div className="mt-3 overflow-x-auto rounded-lg border bg-card"><table className="w-full text-sm"><thead className="border-b text-left text-xs uppercase text-muted-foreground"><tr>{["Cliente","Contato","Plano","Adesão","Valor","Status"].map((h)=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map((l)=><tr key={l.id} className="border-b last:border-0"><td className="p-3"><p className="font-medium">{l.name}</p><p className="text-xs text-muted-foreground">{l.cpf?maskCpf(l.cpf):"CPF não informado"}</p></td><td className="p-3">{l.whatsapp||l.phone?maskPhone(l.whatsapp??l.phone??""):"—"}</td><td className="p-3">{l.plans?.name??"—"}</td><td className="p-3">{dateBR(l.sale_date??l.created_at)}</td><td className="p-3">{brl(l.plans?.price)}</td><td className="p-3"><SellerStatus value={l.status}/></td></tr>)}</tbody></table>{!rows.length&&<p className="p-5 text-sm text-muted-foreground">Nenhum cliente encontrado.</p>}</div></div>}