import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useSeller } from "@/lib/auth";
import { brl, dateBR } from "@/lib/format";
import { PageHeader, StatCard } from "@/components/shells";
import { SellerStatus } from "@/components/seller-status";

export const Route = createFileRoute("/_authenticated/vendedor/comissoes")({ head: () => ({ meta: [{ title: "Comissões | Cartão do Bairro" }, { name: "description", content: "Comissões do vendedor." }, { property: "og:title", content: "Comissões | Cartão do Bairro" }, { property: "og:description", content: "Acompanhe comissões geradas e pagas." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Commissions });
function Commissions() { const { data: seller } = useSeller(); const { data: rows } = useQuery({ queryKey: ["seller-commissions-detail", seller?.id], enabled: !!seller?.id, queryFn: async () => { const { data, error } = await supabase.from("seller_commissions").select("*, seller_sales(created_at, amount, plans(name))").eq("seller_id", seller!.id).order("created_at", { ascending: false }); if (error) throw error; return data; }}); const list = rows ?? []; const now = new Date(); const month = list.filter((r) => { const d = new Date(r.created_at); return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear(); }); const paid = list.filter((r) => r.status === "paga"); const pending = list.filter((r) => !["paga","cancelada","estornada"].includes(r.status)); const sum = (values: typeof list) => values.reduce((total, row) => total + Number(row.amount), 0); const next = pending.map((r) => r.due_date).filter(Boolean).sort()[0]; return <div><PageHeader title="Comissões" description="Valores calculados automaticamente pelas regras da administração"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><StatCard label="No mês" value={brl(sum(month))} tone="brand"/><StatCard label="Acumulada" value={brl(sum(list))}/><StatCard label="Já paga" value={brl(sum(paid))}/><StatCard label="Pendente" value={brl(sum(pending))} tone="ink"/><StatCard label="Próximo pagamento" value={dateBR(next)}/></div><div className="mt-5 overflow-x-auto rounded-lg border bg-card"><table className="w-full text-sm"><thead className="border-b text-left text-xs uppercase text-muted-foreground"><tr>{["Data","Cliente","Plano","Venda","Comissão","Status"].map((h) => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{list.map((r) => <tr className="border-b last:border-0" key={r.id}><td className="p-3">{dateBR(r.created_at)}</td><td className="p-3 font-medium">Cliente</td><td className="p-3">{r.seller_sales?.plans?.name ?? "—"}</td><td className="p-3">{brl(r.seller_sales?.amount)}</td><td className="p-3 font-bold">{brl(r.amount)}</td><td className="p-3"><SellerStatus value={r.status}/></td></tr>)}</tbody></table>{!list.length && <p className="p-5 text-sm text-muted-foreground">Nenhuma comissão registrada.</p>}</div></div>; }