import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, CheckCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
import { dateTimeBR } from "@/lib/format";
import { PageHeader } from "@/components/shells";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/_authenticated/vendedor/notificacoes")({head:()=>({meta:[{title:"Notificações do vendedor | Cartão do Bairro"},{name:"description",content:"Avisos de vendas, pagamentos e comissões."},{property:"og:title",content:"Notificações do vendedor | Cartão do Bairro"},{property:"og:description",content:"Avisos comerciais em tempo real."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:SellerNotifications});
function SellerNotifications(){const{user}=useAuth();const qc=useQueryClient();const{data:items}=useQuery({queryKey:["seller-notifications",user?.id],enabled:!!user,queryFn:async()=>{const{data,error}=await supabase.from("notifications").select("*").eq("user_id",user!.id).order("created_at",{ascending:false}).limit(100);if(error)throw error;return data;}});const mark=useMutation({mutationFn:async()=>{const{error}=await supabase.from("notifications").update({read_at:new Date().toISOString()}).eq("user_id",user!.id).is("read_at",null);if(error)throw error;},onSuccess:()=>qc.invalidateQueries({queryKey:["seller-notifications"]})});const unread=items?.filter((n)=>!n.read_at).length??0;return <div><PageHeader title="Notificações" description={unread?`${unread} aviso(s) não lido(s)`:"Tudo em dia"} action={unread?<Button variant="outline" onClick={()=>mark.mutate()}><CheckCheck className="size-4"/>Marcar como lidas</Button>:undefined}/><div className="space-y-2">{items?.map((n)=><article key={n.id} className={`rounded-lg border p-4 ${n.read_at?"bg-card":"border-primary/40 bg-primary/5"}`}><div className="flex gap-3"><Bell className="mt-0.5 size-4 text-primary"/><div className="flex-1"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-sm font-bold">{n.title}</h2><time className="text-xs text-muted-foreground">{dateTimeBR(n.created_at)}</time></div>{n.message&&<p className="mt-1 text-sm text-muted-foreground">{n.message}</p>}</div></div></article>)}{!items?.length&&<p className="rounded-lg border bg-card p-5 text-sm text-muted-foreground">Nenhuma notificação por enquanto.</p>}</div></div>}