/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ParceriaRouteImport } from './routes/parceria'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedParceiroRouteImport } from './routes/_authenticated/parceiro'
import { Route as AuthenticatedVendedorRouteImport } from './routes/_authenticated/vendedor'
import { Route as EmpresaIdRouteImport } from './routes/empresa.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAssinaturasRouteImport } from './routes/_authenticated/admin.assinaturas'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminFluxoDeCaixaRouteImport } from './routes/_authenticated/admin.fluxo-de-caixa'
import { Route as AuthenticatedAdminParceirosRouteImport } from './routes/_authenticated/admin.parceiros'
import { Route as AuthenticatedAdminPlanosRouteImport } from './routes/_authenticated/admin.planos'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin.suporte'
import { Route as AuthenticatedAdminVendedoresRouteImport } from './routes/_authenticated/admin.vendedores'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppCartaoRouteImport } from './routes/_authenticated/app.cartao'
import { Route as AuthenticatedAppContaRouteImport } from './routes/_authenticated/app.conta'
import { Route as AuthenticatedAppDependentesRouteImport } from './routes/_authenticated/app.dependentes'
import { Route as AuthenticatedAppExplorarRouteImport } from './routes/_authenticated/app.explorar'
import { Route as AuthenticatedAppFavoritosRouteImport } from './routes/_authenticated/app.favoritos'
import { Route as AuthenticatedAppNotificacoesRouteImport } from './routes/_authenticated/app.notificacoes'
import { Route as AuthenticatedAppPagamentoRouteImport } from './routes/_authenticated/app.pagamento'
import { Route as AuthenticatedAppPlanosRouteImport } from './routes/_authenticated/app.planos'
import { Route as AuthenticatedAppSuporteRouteImport } from './routes/_authenticated/app.suporte'
import { Route as AuthenticatedParceiroIndexRouteImport } from './routes/_authenticated/parceiro.index'
import { Route as AuthenticatedParceiroBeneficiosRouteImport } from './routes/_authenticated/parceiro.beneficios'
import { Route as AuthenticatedParceiroEquipeRouteImport } from './routes/_authenticated/parceiro.equipe'
import { Route as AuthenticatedParceiroPerfilRouteImport } from './routes/_authenticated/parceiro.perfil'
import { Route as AuthenticatedParceiroRelatoriosRouteImport } from './routes/_authenticated/parceiro.relatorios'
import { Route as AuthenticatedParceiroValidarRouteImport } from './routes/_authenticated/parceiro.validar'
import { Route as AuthenticatedVendedorIndexRouteImport } from './routes/_authenticated/vendedor.index'
import { Route as AuthenticatedVendedorLeadsRouteImport } from './routes/_authenticated/vendedor.leads'
import { Route as AuthenticatedVendedorVendasRouteImport } from './routes/_authenticated/vendedor.vendas'
import { Route as AuthenticatedAdminClientesIndexRouteImport } from './routes/_authenticated/admin.clientes.index'
import { Route as AuthenticatedAdminClientesIdRouteImport } from './routes/_authenticated/admin.clientes.$id'
import { Route as AuthenticatedAdminParceirosIdRouteImport } from './routes/_authenticated/admin.parceiros.$id'
import { Route as ApiPublicWebhooksInfinitepayRouteImport } from './routes/api/public/webhooks/infinitepay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceriaRoute = ParceriaRouteImport.update({
  id: '/parceria',
  path: '/parceria',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParceiroRoute = AuthenticatedParceiroRouteImport.update({
  id: '/parceiro',
  path: '/parceiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedorRoute = AuthenticatedVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EmpresaIdRoute = EmpresaIdRouteImport.update({
  id: '/empresa/$id',
  path: '/empresa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAssinaturasRoute =
  AuthenticatedAdminAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFluxoDeCaixaRoute =
  AuthenticatedAdminFluxoDeCaixaRouteImport.update({
    id: '/fluxo-de-caixa',
    path: '/fluxo-de-caixa',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParceirosRoute =
  AuthenticatedAdminParceirosRouteImport.update({
    id: '/parceiros',
    path: '/parceiros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlanosRoute =
  AuthenticatedAdminPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVendedoresRoute =
  AuthenticatedAdminVendedoresRouteImport.update({
    id: '/vendedores',
    path: '/vendedores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCartaoRoute = AuthenticatedAppCartaoRouteImport.update({
  id: '/cartao',
  path: '/cartao',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppContaRoute = AuthenticatedAppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDependentesRoute =
  AuthenticatedAppDependentesRouteImport.update({
    id: '/dependentes',
    path: '/dependentes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExplorarRoute =
  AuthenticatedAppExplorarRouteImport.update({
    id: '/explorar',
    path: '/explorar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFavoritosRoute =
  AuthenticatedAppFavoritosRouteImport.update({
    id: '/favoritos',
    path: '/favoritos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificacoesRoute =
  AuthenticatedAppNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPagamentoRoute =
  AuthenticatedAppPagamentoRouteImport.update({
    id: '/pagamento',
    path: '/pagamento',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlanosRoute = AuthenticatedAppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSuporteRoute = AuthenticatedAppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedParceiroIndexRoute =
  AuthenticatedParceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedParceiroRoute,
  } as any)
const AuthenticatedParceiroBeneficiosRoute =
  AuthenticatedParceiroBeneficiosRouteImport.update({
    id: '/beneficios',
    path: '/beneficios',
    getParentRoute: () => AuthenticatedParceiroRoute,
  } as any)
const AuthenticatedParceiroEquipeRoute =
  AuthenticatedParceiroEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedParceiroRoute,
  } as any)
const AuthenticatedParceiroPerfilRoute =
  AuthenticatedParceiroPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedParceiroRoute,
  } as any)
const AuthenticatedParceiroRelatoriosRoute =
  AuthenticatedParceiroRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedParceiroRoute,
  } as any)
const AuthenticatedParceiroValidarRoute =
  AuthenticatedParceiroValidarRouteImport.update({
    id: '/validar',
    path: '/validar',
    getParentRoute: () => AuthenticatedParceiroRoute,
  } as any)
const AuthenticatedVendedorIndexRoute =
  AuthenticatedVendedorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorLeadsRoute =
  AuthenticatedVendedorLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorVendasRoute =
  AuthenticatedVendedorVendasRouteImport.update({
    id: '/vendas',
    path: '/vendas',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedAdminClientesIndexRoute =
  AuthenticatedAdminClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesIdRoute =
  AuthenticatedAdminClientesIdRouteImport.update({
    id: '/clientes/$id',
    path: '/clientes/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParceirosIdRoute =
  AuthenticatedAdminParceirosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminParceirosRoute,
  } as any)
const ApiPublicWebhooksInfinitepayRoute =
  ApiPublicWebhooksInfinitepayRouteImport.update({
    id: '/api/public/webhooks/infinitepay',
    path: '/api/public/webhooks/infinitepay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/parceria': typeof ParceriaRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/parceiro': typeof AuthenticatedParceiroRouteWithChildren
  '/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/empresa/$id': typeof EmpresaIdRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/fluxo-de-caixa': typeof AuthenticatedAdminFluxoDeCaixaRoute
  '/admin/parceiros': typeof AuthenticatedAdminParceirosRouteWithChildren
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRoute
  '/app/cartao': typeof AuthenticatedAppCartaoRoute
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/app/dependentes': typeof AuthenticatedAppDependentesRoute
  '/app/explorar': typeof AuthenticatedAppExplorarRoute
  '/app/favoritos': typeof AuthenticatedAppFavoritosRoute
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/pagamento': typeof AuthenticatedAppPagamentoRoute
  '/app/planos': typeof AuthenticatedAppPlanosRoute
  '/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/parceiro/beneficios': typeof AuthenticatedParceiroBeneficiosRoute
  '/parceiro/equipe': typeof AuthenticatedParceiroEquipeRoute
  '/parceiro/perfil': typeof AuthenticatedParceiroPerfilRoute
  '/parceiro/relatorios': typeof AuthenticatedParceiroRelatoriosRoute
  '/parceiro/validar': typeof AuthenticatedParceiroValidarRoute
  '/vendedor/leads': typeof AuthenticatedVendedorLeadsRoute
  '/vendedor/vendas': typeof AuthenticatedVendedorVendasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/parceiro/': typeof AuthenticatedParceiroIndexRoute
  '/vendedor/': typeof AuthenticatedVendedorIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/parceiros/$id': typeof AuthenticatedAdminParceirosIdRoute
  '/api/public/webhooks/infinitepay': typeof ApiPublicWebhooksInfinitepayRoute
  '/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/parceria': typeof ParceriaRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/fluxo-de-caixa': typeof AuthenticatedAdminFluxoDeCaixaRoute
  '/admin/parceiros': typeof AuthenticatedAdminParceirosRouteWithChildren
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRoute
  '/app/cartao': typeof AuthenticatedAppCartaoRoute
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/app/dependentes': typeof AuthenticatedAppDependentesRoute
  '/app/explorar': typeof AuthenticatedAppExplorarRoute
  '/app/favoritos': typeof AuthenticatedAppFavoritosRoute
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/pagamento': typeof AuthenticatedAppPagamentoRoute
  '/app/planos': typeof AuthenticatedAppPlanosRoute
  '/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/parceiro/beneficios': typeof AuthenticatedParceiroBeneficiosRoute
  '/parceiro/equipe': typeof AuthenticatedParceiroEquipeRoute
  '/parceiro/perfil': typeof AuthenticatedParceiroPerfilRoute
  '/parceiro/relatorios': typeof AuthenticatedParceiroRelatoriosRoute
  '/parceiro/validar': typeof AuthenticatedParceiroValidarRoute
  '/vendedor/leads': typeof AuthenticatedVendedorLeadsRoute
  '/vendedor/vendas': typeof AuthenticatedVendedorVendasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/parceiro': typeof AuthenticatedParceiroIndexRoute
  '/vendedor': typeof AuthenticatedVendedorIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/parceiros/$id': typeof AuthenticatedAdminParceirosIdRoute
  '/api/public/webhooks/infinitepay': typeof ApiPublicWebhooksInfinitepayRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/parceria': typeof ParceriaRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/parceiro': typeof AuthenticatedParceiroRouteWithChildren
  '/_authenticated/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/empresa/$id': typeof EmpresaIdRoute
  '/_authenticated/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/fluxo-de-caixa': typeof AuthenticatedAdminFluxoDeCaixaRoute
  '/_authenticated/admin/parceiros': typeof AuthenticatedAdminParceirosRouteWithChildren
  '/_authenticated/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/admin/vendedores': typeof AuthenticatedAdminVendedoresRoute
  '/_authenticated/app/cartao': typeof AuthenticatedAppCartaoRoute
  '/_authenticated/app/conta': typeof AuthenticatedAppContaRoute
  '/_authenticated/app/dependentes': typeof AuthenticatedAppDependentesRoute
  '/_authenticated/app/explorar': typeof AuthenticatedAppExplorarRoute
  '/_authenticated/app/favoritos': typeof AuthenticatedAppFavoritosRoute
  '/_authenticated/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/_authenticated/app/pagamento': typeof AuthenticatedAppPagamentoRoute
  '/_authenticated/app/planos': typeof AuthenticatedAppPlanosRoute
  '/_authenticated/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/_authenticated/parceiro/beneficios': typeof AuthenticatedParceiroBeneficiosRoute
  '/_authenticated/parceiro/equipe': typeof AuthenticatedParceiroEquipeRoute
  '/_authenticated/parceiro/perfil': typeof AuthenticatedParceiroPerfilRoute
  '/_authenticated/parceiro/relatorios': typeof AuthenticatedParceiroRelatoriosRoute
  '/_authenticated/parceiro/validar': typeof AuthenticatedParceiroValidarRoute
  '/_authenticated/vendedor/leads': typeof AuthenticatedVendedorLeadsRoute
  '/_authenticated/vendedor/vendas': typeof AuthenticatedVendedorVendasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/parceiro/': typeof AuthenticatedParceiroIndexRoute
  '/_authenticated/vendedor/': typeof AuthenticatedVendedorIndexRoute
  '/_authenticated/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/_authenticated/admin/parceiros/$id': typeof AuthenticatedAdminParceirosIdRoute
  '/api/public/webhooks/infinitepay': typeof ApiPublicWebhooksInfinitepayRoute
  '/_authenticated/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/parceria'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/app'
    | '/parceiro'
    | '/vendedor'
    | '/empresa/$id'
    | '/admin/assinaturas'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/financeiro'
    | '/admin/fluxo-de-caixa'
    | '/admin/parceiros'
    | '/admin/planos'
    | '/admin/suporte'
    | '/admin/vendedores'
    | '/app/cartao'
    | '/app/conta'
    | '/app/dependentes'
    | '/app/explorar'
    | '/app/favoritos'
    | '/app/notificacoes'
    | '/app/pagamento'
    | '/app/planos'
    | '/app/suporte'
    | '/parceiro/beneficios'
    | '/parceiro/equipe'
    | '/parceiro/perfil'
    | '/parceiro/relatorios'
    | '/parceiro/validar'
    | '/vendedor/leads'
    | '/vendedor/vendas'
    | '/admin/'
    | '/app/'
    | '/parceiro/'
    | '/vendedor/'
    | '/admin/clientes/$id'
    | '/admin/parceiros/$id'
    | '/api/public/webhooks/infinitepay'
    | '/admin/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/parceria'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/empresa/$id'
    | '/admin/assinaturas'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/financeiro'
    | '/admin/fluxo-de-caixa'
    | '/admin/parceiros'
    | '/admin/planos'
    | '/admin/suporte'
    | '/admin/vendedores'
    | '/app/cartao'
    | '/app/conta'
    | '/app/dependentes'
    | '/app/explorar'
    | '/app/favoritos'
    | '/app/notificacoes'
    | '/app/pagamento'
    | '/app/planos'
    | '/app/suporte'
    | '/parceiro/beneficios'
    | '/parceiro/equipe'
    | '/parceiro/perfil'
    | '/parceiro/relatorios'
    | '/parceiro/validar'
    | '/vendedor/leads'
    | '/vendedor/vendas'
    | '/admin'
    | '/app'
    | '/parceiro'
    | '/vendedor'
    | '/admin/clientes/$id'
    | '/admin/parceiros/$id'
    | '/api/public/webhooks/infinitepay'
    | '/admin/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/parceria'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/parceiro'
    | '/_authenticated/vendedor'
    | '/empresa/$id'
    | '/_authenticated/admin/assinaturas'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/fluxo-de-caixa'
    | '/_authenticated/admin/parceiros'
    | '/_authenticated/admin/planos'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/vendedores'
    | '/_authenticated/app/cartao'
    | '/_authenticated/app/conta'
    | '/_authenticated/app/dependentes'
    | '/_authenticated/app/explorar'
    | '/_authenticated/app/favoritos'
    | '/_authenticated/app/notificacoes'
    | '/_authenticated/app/pagamento'
    | '/_authenticated/app/planos'
    | '/_authenticated/app/suporte'
    | '/_authenticated/parceiro/beneficios'
    | '/_authenticated/parceiro/equipe'
    | '/_authenticated/parceiro/perfil'
    | '/_authenticated/parceiro/relatorios'
    | '/_authenticated/parceiro/validar'
    | '/_authenticated/vendedor/leads'
    | '/_authenticated/vendedor/vendas'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/parceiro/'
    | '/_authenticated/vendedor/'
    | '/_authenticated/admin/clientes/$id'
    | '/_authenticated/admin/parceiros/$id'
    | '/api/public/webhooks/infinitepay'
    | '/_authenticated/admin/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ParceriaRoute: typeof ParceriaRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  EmpresaIdRoute: typeof EmpresaIdRoute
  ApiPublicWebhooksInfinitepayRoute: typeof ApiPublicWebhooksInfinitepayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceria': {
      id: '/parceria'
      path: '/parceria'
      fullPath: '/parceria'
      preLoaderRoute: typeof ParceriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiro': {
      id: '/_authenticated/parceiro'
      path: '/parceiro'
      fullPath: '/parceiro'
      preLoaderRoute: typeof AuthenticatedParceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedor': {
      id: '/_authenticated/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof AuthenticatedVendedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/empresa/$id': {
      id: '/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/empresa/$id'
      preLoaderRoute: typeof EmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assinaturas': {
      id: '/_authenticated/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AuthenticatedAdminAssinaturasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fluxo-de-caixa': {
      id: '/_authenticated/admin/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/admin/fluxo-de-caixa'
      preLoaderRoute: typeof AuthenticatedAdminFluxoDeCaixaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parceiros': {
      id: '/_authenticated/admin/parceiros'
      path: '/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AuthenticatedAdminParceirosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/planos': {
      id: '/_authenticated/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AuthenticatedAdminPlanosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vendedores': {
      id: '/_authenticated/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cartao': {
      id: '/_authenticated/app/cartao'
      path: '/cartao'
      fullPath: '/app/cartao'
      preLoaderRoute: typeof AuthenticatedAppCartaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conta': {
      id: '/_authenticated/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AuthenticatedAppContaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dependentes': {
      id: '/_authenticated/app/dependentes'
      path: '/dependentes'
      fullPath: '/app/dependentes'
      preLoaderRoute: typeof AuthenticatedAppDependentesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/explorar': {
      id: '/_authenticated/app/explorar'
      path: '/explorar'
      fullPath: '/app/explorar'
      preLoaderRoute: typeof AuthenticatedAppExplorarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/favoritos': {
      id: '/_authenticated/app/favoritos'
      path: '/favoritos'
      fullPath: '/app/favoritos'
      preLoaderRoute: typeof AuthenticatedAppFavoritosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notificacoes': {
      id: '/_authenticated/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AuthenticatedAppNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pagamento': {
      id: '/_authenticated/app/pagamento'
      path: '/pagamento'
      fullPath: '/app/pagamento'
      preLoaderRoute: typeof AuthenticatedAppPagamentoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/planos': {
      id: '/_authenticated/app/planos'
      path: '/planos'
      fullPath: '/app/planos'
      preLoaderRoute: typeof AuthenticatedAppPlanosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/suporte': {
      id: '/_authenticated/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AuthenticatedAppSuporteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/parceiro/': {
      id: '/_authenticated/parceiro/'
      path: '/'
      fullPath: '/parceiro/'
      preLoaderRoute: typeof AuthenticatedParceiroIndexRouteImport
      parentRoute: typeof AuthenticatedParceiroRoute
    }
    '/_authenticated/parceiro/beneficios': {
      id: '/_authenticated/parceiro/beneficios'
      path: '/beneficios'
      fullPath: '/parceiro/beneficios'
      preLoaderRoute: typeof AuthenticatedParceiroBeneficiosRouteImport
      parentRoute: typeof AuthenticatedParceiroRoute
    }
    '/_authenticated/parceiro/equipe': {
      id: '/_authenticated/parceiro/equipe'
      path: '/equipe'
      fullPath: '/parceiro/equipe'
      preLoaderRoute: typeof AuthenticatedParceiroEquipeRouteImport
      parentRoute: typeof AuthenticatedParceiroRoute
    }
    '/_authenticated/parceiro/perfil': {
      id: '/_authenticated/parceiro/perfil'
      path: '/perfil'
      fullPath: '/parceiro/perfil'
      preLoaderRoute: typeof AuthenticatedParceiroPerfilRouteImport
      parentRoute: typeof AuthenticatedParceiroRoute
    }
    '/_authenticated/parceiro/relatorios': {
      id: '/_authenticated/parceiro/relatorios'
      path: '/relatorios'
      fullPath: '/parceiro/relatorios'
      preLoaderRoute: typeof AuthenticatedParceiroRelatoriosRouteImport
      parentRoute: typeof AuthenticatedParceiroRoute
    }
    '/_authenticated/parceiro/validar': {
      id: '/_authenticated/parceiro/validar'
      path: '/validar'
      fullPath: '/parceiro/validar'
      preLoaderRoute: typeof AuthenticatedParceiroValidarRouteImport
      parentRoute: typeof AuthenticatedParceiroRoute
    }
    '/_authenticated/vendedor/': {
      id: '/_authenticated/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof AuthenticatedVendedorIndexRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/leads': {
      id: '/_authenticated/vendedor/leads'
      path: '/leads'
      fullPath: '/vendedor/leads'
      preLoaderRoute: typeof AuthenticatedVendedorLeadsRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/vendas': {
      id: '/_authenticated/vendedor/vendas'
      path: '/vendas'
      fullPath: '/vendedor/vendas'
      preLoaderRoute: typeof AuthenticatedVendedorVendasRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/admin/clientes/': {
      id: '/_authenticated/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AuthenticatedAdminClientesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes/$id': {
      id: '/_authenticated/admin/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parceiros/$id': {
      id: '/_authenticated/admin/parceiros/$id'
      path: '/$id'
      fullPath: '/admin/parceiros/$id'
      preLoaderRoute: typeof AuthenticatedAdminParceirosIdRouteImport
      parentRoute: typeof AuthenticatedAdminParceirosRoute
    }
    '/api/public/webhooks/infinitepay': {
      id: '/api/public/webhooks/infinitepay'
      path: '/api/public/webhooks/infinitepay'
      fullPath: '/api/public/webhooks/infinitepay'
      preLoaderRoute: typeof ApiPublicWebhooksInfinitepayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminParceirosRouteChildren {
  AuthenticatedAdminParceirosIdRoute: typeof AuthenticatedAdminParceirosIdRoute
}

const AuthenticatedAdminParceirosRouteChildren: AuthenticatedAdminParceirosRouteChildren =
  {
    AuthenticatedAdminParceirosIdRoute: AuthenticatedAdminParceirosIdRoute,
  }

const AuthenticatedAdminParceirosRouteWithChildren =
  AuthenticatedAdminParceirosRoute._addFileChildren(
    AuthenticatedAdminParceirosRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssinaturasRoute: typeof AuthenticatedAdminAssinaturasRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminFluxoDeCaixaRoute: typeof AuthenticatedAdminFluxoDeCaixaRoute
  AuthenticatedAdminParceirosRoute: typeof AuthenticatedAdminParceirosRouteWithChildren
  AuthenticatedAdminPlanosRoute: typeof AuthenticatedAdminPlanosRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminVendedoresRoute: typeof AuthenticatedAdminVendedoresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientesIdRoute: typeof AuthenticatedAdminClientesIdRoute
  AuthenticatedAdminClientesIndexRoute: typeof AuthenticatedAdminClientesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssinaturasRoute: AuthenticatedAdminAssinaturasRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminFluxoDeCaixaRoute: AuthenticatedAdminFluxoDeCaixaRoute,
  AuthenticatedAdminParceirosRoute:
    AuthenticatedAdminParceirosRouteWithChildren,
  AuthenticatedAdminPlanosRoute: AuthenticatedAdminPlanosRoute,
  AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
  AuthenticatedAdminVendedoresRoute: AuthenticatedAdminVendedoresRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClientesIdRoute: AuthenticatedAdminClientesIdRoute,
  AuthenticatedAdminClientesIndexRoute: AuthenticatedAdminClientesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCartaoRoute: typeof AuthenticatedAppCartaoRoute
  AuthenticatedAppContaRoute: typeof AuthenticatedAppContaRoute
  AuthenticatedAppDependentesRoute: typeof AuthenticatedAppDependentesRoute
  AuthenticatedAppExplorarRoute: typeof AuthenticatedAppExplorarRoute
  AuthenticatedAppFavoritosRoute: typeof AuthenticatedAppFavoritosRoute
  AuthenticatedAppNotificacoesRoute: typeof AuthenticatedAppNotificacoesRoute
  AuthenticatedAppPagamentoRoute: typeof AuthenticatedAppPagamentoRoute
  AuthenticatedAppPlanosRoute: typeof AuthenticatedAppPlanosRoute
  AuthenticatedAppSuporteRoute: typeof AuthenticatedAppSuporteRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCartaoRoute: AuthenticatedAppCartaoRoute,
  AuthenticatedAppContaRoute: AuthenticatedAppContaRoute,
  AuthenticatedAppDependentesRoute: AuthenticatedAppDependentesRoute,
  AuthenticatedAppExplorarRoute: AuthenticatedAppExplorarRoute,
  AuthenticatedAppFavoritosRoute: AuthenticatedAppFavoritosRoute,
  AuthenticatedAppNotificacoesRoute: AuthenticatedAppNotificacoesRoute,
  AuthenticatedAppPagamentoRoute: AuthenticatedAppPagamentoRoute,
  AuthenticatedAppPlanosRoute: AuthenticatedAppPlanosRoute,
  AuthenticatedAppSuporteRoute: AuthenticatedAppSuporteRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedParceiroRouteChildren {
  AuthenticatedParceiroBeneficiosRoute: typeof AuthenticatedParceiroBeneficiosRoute
  AuthenticatedParceiroEquipeRoute: typeof AuthenticatedParceiroEquipeRoute
  AuthenticatedParceiroPerfilRoute: typeof AuthenticatedParceiroPerfilRoute
  AuthenticatedParceiroRelatoriosRoute: typeof AuthenticatedParceiroRelatoriosRoute
  AuthenticatedParceiroValidarRoute: typeof AuthenticatedParceiroValidarRoute
  AuthenticatedParceiroIndexRoute: typeof AuthenticatedParceiroIndexRoute
}

const AuthenticatedParceiroRouteChildren: AuthenticatedParceiroRouteChildren = {
  AuthenticatedParceiroBeneficiosRoute: AuthenticatedParceiroBeneficiosRoute,
  AuthenticatedParceiroEquipeRoute: AuthenticatedParceiroEquipeRoute,
  AuthenticatedParceiroPerfilRoute: AuthenticatedParceiroPerfilRoute,
  AuthenticatedParceiroRelatoriosRoute: AuthenticatedParceiroRelatoriosRoute,
  AuthenticatedParceiroValidarRoute: AuthenticatedParceiroValidarRoute,
  AuthenticatedParceiroIndexRoute: AuthenticatedParceiroIndexRoute,
}

const AuthenticatedParceiroRouteWithChildren =
  AuthenticatedParceiroRoute._addFileChildren(
    AuthenticatedParceiroRouteChildren,
  )

interface AuthenticatedVendedorRouteChildren {
  AuthenticatedVendedorLeadsRoute: typeof AuthenticatedVendedorLeadsRoute
  AuthenticatedVendedorVendasRoute: typeof AuthenticatedVendedorVendasRoute
  AuthenticatedVendedorIndexRoute: typeof AuthenticatedVendedorIndexRoute
}

const AuthenticatedVendedorRouteChildren: AuthenticatedVendedorRouteChildren = {
  AuthenticatedVendedorLeadsRoute: AuthenticatedVendedorLeadsRoute,
  AuthenticatedVendedorVendasRoute: AuthenticatedVendedorVendasRoute,
  AuthenticatedVendedorIndexRoute: AuthenticatedVendedorIndexRoute,
}

const AuthenticatedVendedorRouteWithChildren =
  AuthenticatedVendedorRoute._addFileChildren(
    AuthenticatedVendedorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedParceiroRoute: typeof AuthenticatedParceiroRouteWithChildren
  AuthenticatedVendedorRoute: typeof AuthenticatedVendedorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedParceiroRoute: AuthenticatedParceiroRouteWithChildren,
  AuthenticatedVendedorRoute: AuthenticatedVendedorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ParceriaRoute: ParceriaRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  EmpresaIdRoute: EmpresaIdRoute,
  ApiPublicWebhooksInfinitepayRoute: ApiPublicWebhooksInfinitepayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
